### ISSUE TITLE
Issue when drag item

### ISSUE THREAD

**Issue by huyphams** [robin/LYTabView#10]
Drag item is a nice feature when we want to re-order tab item. But when item was packed, we can't drag it out. Any idea for this?
I just thought
1. We will move out it when selected in pack (move to last tab for example).
2. Using an other solution to pack tabs.

Sorry for annoying this morning, but I'm actually using it and got some trouble 😸

**Comment by robin** [comment]
I applied a patch to support dragging packed items in following way:

1. when a packed item is selected, the last tab is always selected to represent the selected packed item.
2. you can drag and drop the last tab.

Can you have a try?

**Comment by huyphams** [comment]
Sure, I trying now

**Comment by huyphams** [comment]
Just crashed this line:
```
    private var packedTabViewItems: [NSTabViewItem] = [NSTabViewItem]()
    private var lastUnpackedItem: NSTabViewItem {
      Logger.debug("=============== \( self.tabViewItems.count) - \(self.tabItemViews().count-1)")
        return self.tabViewItems[self.tabItemViews().count-1]
    }

```
Debug value:
```
[DEBUG] lastUnpackedItem:150: =============== 1 - 0
[DEBUG] lastUnpackedItem:150: =============== 2 - 1
[DEBUG] lastUnpackedItem:150: =============== 3 - 2
[DEBUG] lastUnpackedItem:150: =============== 2 - 2
```
Seem out of range

**Comment by robin** [comment]
I got the bug. I am trying to fix it.

**Comment by robin** [comment]
I've fixed the crash. Can you have a try? Thanks!

**Comment by huyphams** [comment]
Sure

**Comment by huyphams** [comment]
works great 👍
