### ISSUE TITLE
Close tab to the Right 

### ISSUE THREAD

**Issue by huyphams** [robin/LYTabView#11]
Hi @robin 
It would be great if we can add a menu `close tab to the right` like Google Chrome does, I found it is a common way to close tab for end user.
I can make a pull request for this feature 💃 
<img width="512" alt="screen shot 2017-04-27 at 7 22 03 pm" src="https://cloud.githubusercontent.com/assets/3654622/25483196/0d641a68-2b7f-11e7-80ce-3ac02140e911.png">
Huy.

**Comment by robin** [comment]
good

**Comment by robin** [comment]
fixed in the latest build. Have a try. Thanks.
