### ISSUE TITLE
Issues when add target.

### ISSUE THREAD

**Issue by huyphams** [robin/LYTabView#7]
because 
```
    open var addNewTabButtonAction: Selector?
```
https://github.com/robin/LYTabView/blob/master/LYTabView/LYTabBarView.swift#L141
Is strong, so if I add tabView as subview of View A and then set selector
```
 addNewTabButtonAction = A
```
The view will never release.

It would be great if we change it to 
```
    open weak var addNewTabButtonAction: Selector?
```
I will give a pull request if you agree.
Thanks

**Comment by robin** [comment]
Good catch! The root cause should be the ownership of addNewTabButtonTarget. I've applied a patch to fix the issue and made it more flexible. Can you have a look?

**Comment by huyphams** [comment]
Oh sorry I'm wrong, it should be`addNewTabButtonTarget` sure, will take a look
