### ISSUE TITLE
Add removeNewTabButtonTarget and action

### ISSUE THREAD

**Issue by huyphams** [robin/LYTabView#8]
Hi @robin ,
We have 
```
    open weak var addNewTabButtonTarget: AnyObject?
    open var addNewTabButtonAction: Selector?
```
for adding button purpose, how do you think if we add 
```
   open weak var removeTabButtonTarget: AnyObject?
   open var removeTabButtonAction: Selector?
```
For trigger event when we close tab, because I want to trigger an event remove ViewController owner of view which was managed by tab item.
Implement NSTabViewDelegate seem clumsy.

**Comment by robin** [comment]
I think it's not actually an action. What you need looks more like an afterward notification, delegation is a more proper way to do it.

**Comment by huyphams** [comment]
My situation,

In main window, I have an array of ViewController
``` 
internal var viewControllers = [NSViewController]()
```
When add a new tab:
```
    let item = NSTabViewItem()
    let viewController = ViewController()
    item.label = label
    item.view = viewController.view

    self.tabView.tabBarView.addTabViewItem(item, animated: false)
    self.tabView.selectTabViewItemAtIndex(self.viewControllers.count)
```
When I closed tab by button on tab item or right click menu of tab bar I need to remove viewController from array.
delegation is great but seem you didn't implement any delegate?

**Comment by robin** [comment]
There's a tabViewDidChangeNumberOfTabViewItems but may not very suitable to your case. I may need to extend the NSTabViewDelegate to include this.

**Comment by huyphams** [comment]
Solved thanks you 👍
